### ISSUE TITLE
Authorized Content Access via Amplify-Video

### ISSUE THREAD

**Issue by axptwig** [awslabs/amplify-video#10]
**Is your feature request related to a problem? Please describe.**
As an Amplify-Video user, I'd like to authenticate uers via amplify auth and authorize access to specific amplify-video resources (livestream or VOD) through cloudfront or directly from an origin (S3, mediastore, mediapackage)

**Describe the solution you'd like**
When creating an amplify-video resource via the CLI, ask if authorized access is required. If yes, create/use existing project cognito user-pool to authenticate and authorize access to resources. For resources fronted by CDN, content access should be limited *only* to the origin via cloudfront OAID and signed-cookies should be set via Lambda managed by amplify-video.

**Describe alternatives you've considered**

**Additional context**

**Comment by wizage** [comment]
This will be taken into account when we release #4. Keeping open for tracking purposes.

**Comment by smp** [comment]
@wizage - in #4 you have cloudfront represented, but will the initial release include private content / auth through cloudfront signed URLs in addition to S3 Signed URLs? If so, we'll need to use lambda to authorize access by setting a signed cookie for authenticated users. There's no way to serve private content through cloudfront with just cognito. Additionally, the signing key requires root AWS account access and should be stored in parameter store..

**Comment by smp** [comment]
Also, signed-url access is not specific to VOD, we should probably scope this ticket to all content authZ through amplify-video.

**Comment by houmark** [comment]
I'm also interested in authenticated access to VOD and live streaming through Amplify (using GraphQL/AppSync?).

Any development on that?

**Comment by wizage** [comment]
@houmark what type of Auth access are you looking for. Right now I am planning on doing either enable or disabling access control. It would look similar to Netflix as it would just confirm that a user has a subscription. Are you looking for more fine grained then this?

**Comment by houmark** [comment]
My use case is a membership service, it's built on AWS Amplify with Cognito for users and AppSync / GraphQL. Additionally to the Cognito User we also have an GraphQL / AppSync model called User where we can hook more user related stuff on.

Our requirements are not too complex, but a wish list goes like this:

1. Limit access per video uploaded, so you must be authenticated.
2. Make some videos public (unauthenticated).
3. Maybe use Cognito user groups for finer-grained control per video. So if you are in the standard Cognito group and the video is only available to premium, then you cannot access it. This is not a launch blocker for us though, but would be nice to have.
4. The above is for on demand which will be our primary use case, not sure how this could also apply to live streams which we also plan to do for live webinar sessions?

**Comment by wizage** [comment]
Perfect, this is super helpful for us making decisions going forward.

I will tag you when we start working on this more in depth but this gives us a good going forward point!

**Comment by houmark** [comment]
Great, my only issue is we need to start this implantation very soon. Any ETA on when you start and hope to have improvements in relation to this?

**Comment by wizage** [comment]
We are working every day on it. Phase 1 will be done sometime in the next week. After that we are going to jump right into phase 2. I assume that will be around 1 month as we are creating the CloudFormation from scratch for this section. The release won't be until Re:Invent in December which will come with a blog post. But this fork will have it done way sooner. We are developing a workshop around this plugin so we are completing this plugin way before the workshop.

**Comment by houmark** [comment]
Okay so I’m some way I may be able to use the fork and get it working before release in around a months time?

**Comment by wizage** [comment]
Yep all you would need to do is clone the fork, and run `npm install -g` and then use it as you would with the current amplify video stuff.

**Comment by wizage** [comment]
This is merged.

Support has been added in 2.6.0
