### ISSUE TITLE
'amplify video stop' does not stop the selected live strea,

### ISSUE THREAD

**Issue by AdamTylerLynch** [awslabs/amplify-video#116]
**Describe the bug**
When using 'amplify video stop', the MediaLive stream isn't stopped (idled). I receive the following message: "mylivestream is already running."

**To Reproduce**
1. Make sure you have the latest version of the amplify video plugin.
2. Have a MediaLive stream started
3. Execute 'amplify video stop'
4. Select your stream (mine is 'medialivestream')
5. The plugin returns "mylivestream is already running."

**Expected behavior**
The livestream should be stopped.

**Screenshots**
![Screen Shot 2020-06-24 at 11 21 33 AM](https://user-images.githubusercontent.com/14060912/85585022-a8244200-b60d-11ea-8990-70aea7b3e7db.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Terminal, ZSH shell

**Comment by wizage** [comment]
Fixed with #117
