### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [awslabs/amplify-video#13]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/awslabs/amplify-video/blob/master/package.json#L24

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by wizage** [comment]
Thanks @DanielRuf for pointing this out!
