### ISSUE TITLE
Add support for UHD/4K Live Streaming with Elemental

### ISSUE THREAD

**Issue by smp** [awslabs/amplify-video#149]
**Is your feature request related to a problem? Please describe.**
I would like to support UHD live streams with Elemental Live/Mediastore for 360-degree live streaming

**Describe the solution you'd like**
Add UHD as a selection in profile config steps 

**Describe alternatives you've considered**
Manually editing in the console isn't great..

**Comment by wizage** [comment]
Closed with #151
