### ISSUE TITLE
Running setup-obs returns incorrect streaming URL

### ISSUE THREAD

**Issue by smp** [awslabs/amplify-video#155]
**Describe the bug**
setup-obs command with Amplify-CLI on Windows/WSL provides a url with two rtmps:// URIs when used with Elemental Livestream

{"settings":{"key":"umgstream-dev-p","server":"rtmps://rtmp://44.236.247.70:1935/umgstream-dev-p"},"type":"rtmp_custom"}

**Comment by mstfldmr** [comment]
this is valid for MacOS as well

**Comment by nathanagez** [comment]
@smp @wizage, should we use `RTMPS` or `RTMP` protocol ? The default URL returned by Elemental Livestream uses RTMP protocol but I know that EL supports both.

**Comment by wizage** [comment]
fixed in #183

**Comment by smp** [comment]
According to media live documentation, they do not support RTMPS inputs - @nathanagez did you test with medialive/elemental stack?

https://docs.aws.amazon.com/medialive/latest/ug/inputs-supported-formats.html

**Comment by nathanagez** [comment]
@smp I fixed the PR, @wizage can re-merge it
