### ISSUE TITLE
The Amplify CLI can NOT find command:  video add

### ISSUE THREAD

**Issue by yudao** [awslabs/amplify-video#156]
Hi all,

I'm trying to add this plugin into my amplify project but it's seems not existent for him.

I've already seen #23 issue but it seems resolved in older version.

```bash
> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H2
```
```bash
> amplify --version
4.32.0
```
```bash
> npm install -g amplify-category-video
------------------------------------
Successfully installed Amplify Video
------------------------------------
+ amplify-category-video@3.2.0
```
```bash
> amplify video add
The Amplify CLI can NOT find command:  video add
Scanning for plugins...
Plugin scan successful
```
Thanks for your help.

Yu.

**Comment by wizage** [comment]
Hi Yu,

This sometimes happens randomly and you just need to add the video command manually.

To do so you can run:
`amplify plugin add`

then just paste in the install location of amplify video into the request.

For mac's this is most likely installed at: `/usr/local/lib/node_modules`

**Comment by yudao** [comment]
Hi wizage.

Thanks for the tip, all is working well!

Cheers,

Yu.
