### ISSUE TITLE
Is multiple live stream creation dynamically is possible?

### ISSUE THREAD

**Issue by yudao** [awslabs/amplify-video#162]
**Which Category is your question related to?**
Live Stream

**What AWS Services are you utilizing?**
amplify-video

**Provide additional details e.g. code snippets**

Hi!

After a successful implementation of VOD with this excellent plugin, I'm looking for the live part. On testing live stream I've seen that I must create x live streams needed before I can use them. 

But, I'm coding an application that need to create a live stream when an user need it, so more dynamic than the ```amplify video add``` command which is statically.

So there is a way or a recommendation about let the user create his own live streams? or I should create my custom function to recreate live stream dynamically and no more statically?

Thanks for this great plugin and for your time!

Cheers,
Yu.

**Comment by wizage** [comment]
Currently not today. This is the 2021 major goal for this plugin.

**Comment by yudao** [comment]
Hi @wizage!

Thank you for your time and your answer. I will create my own custom function in the meantime.

Cheers.
Yu.
