### ISSUE TITLE
Failed to start API Mock endpoint Error: Did not find a Lambda matching ARN

### ISSUE THREAD

**Issue by ajonp** [awslabs/amplify-video#165]
**Describe the bug**
When trying to mock the Graph API locally, when using the prebuilt videoObject `token: String @function(name: "ccdvod-{env}-tokenGen")` is used. resulting in an error while mocking.

```
type vodAsset
  @model(subscriptions: { level: public })
  @auth(
    rules: [
      {
        allow: groups
        groups: ["Admin"]
        operations: [create, update, delete, read]
      }
      { allow: private, operations: [read] }
    ]
  ) {
  id: ID!
  title: String!
  description: String!

  #DO NOT EDIT
  video: videoObject @connection
}

#DO NOT EDIT
type videoObject
  @model
  @auth(
    rules: [
      {
        allow: groups
        groups: ["Admin"]
        operations: [create, update, delete, read]
      }
      { allow: private, operations: [read] }
    ]
  ) {
  id: ID!

  token: String @function(name: "ccdvod-{env}-tokenGen")
}
```

**To Reproduce**
1. `amplify video add`
2. at the end select graphl beta
3. `amplify mock`

**Expected behavior**
Either ignore this function or create one that works with mocking.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 87

**Additional context**
For now I am just commenting out the video portion while mocking locally.

**Comment by wizage** [comment]
This is because we don't store the function as an "amplify function". This won't be fixed as the function wouldnt work without being pushed anyways.
