### ISSUE TITLE
Incorrect link to IAM role example in Troubleshooting guide

### ISSUE THREAD

**Issue by vitalbone** [awslabs/amplify-video#168]
**Describe the bug**
In the [Troubleshooting section](https://github.com/awslabs/amplify-video/wiki/Troubleshooting) of the Wiki, there is a link to an example IAM role under the **Q: Why do my resources fail to deploy?** heading.

Unfortunately, the link points to the Troubleshooting Wiki page, aka itself.

**To Reproduce**
1. Go to https://github.com/awslabs/amplify-video/wiki/Troubleshooting
2. Click on _"See **this** example IAM role to make sure you have proper permissions."_
4. Get redirected to the same page

**Expected behavior**
Take the user to a code sample of the described IAM role.

**Screenshots**

<img width="1603" alt="Screen Shot 2020-12-04 at 1 13 42 pm" src="https://user-images.githubusercontent.com/5966259/101113077-b651a200-3632-11eb-9569-10f7da722e54.png">

**Additional context**
Thanks for creating this plugin!

**Comment by wizage** [comment]
Thanks for this! I have updated the wiki with the newest permissions
