### ISSUE TITLE
The Amplify CLI can NOT find command:  video add

### ISSUE THREAD

**Issue by mstfldmr** [awslabs/amplify-video#176]
**Describe the bug**
`amplify add video` does not work 

**To Reproduce**
`amplify --version`
4.40.1

`npm install amplify-category-video -g`
Successfully installed Amplify Video
+ amplify-category-video@3.2.1

`amplify init`

`amplify video add`             
The Amplify CLI can NOT find command:  video add

**Expected behavior**
add video component to the project

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7

**Comment by mstfldmr** [comment]
`amplify plugin add` command solved the problem. The location of the plugin was /Users/myuser/.npm-global/lib/node_modules/amplify-category-video for me.

**Comment by axptwig** [comment]
glad you solved the problem! If you would like to contribute to the project further, we need people to sanity check our docs and would love your feedback on some of the quick starts! Cheers~

**Comment by washington-kibichii** [comment]
> `amplify plugin add` command solved the problem. The location of the plugin was /Users/myuser/.npm-global/lib/node_modules/amplify-category-video for me.

This one worked for me as well.
To get the absolute path for the package after installing plugin check for "postinstall" path provided

```
AdminPanel % npm install amplify-category-video -g

> amplify-category-video@3.9.2 postinstall /Users/user/.nvm/versions/node/v12.14.1/lib/node_modules/amplify-category-video
> node scripts/post-install.js

------------------------------------


Successfully installed Amplify Video


------------------------------------


+ amplify-category-video@3.9.2
updated 1 package in 32.609s
```

**Comment by dickysaylz** [comment]
> `amplify plugin add` command solved the problem. The location of the plugin was /Users/myuser/.npm-global/lib/node_modules/amplify-category-video for me.

absolute legend - this worked for me too!  thanks
