### ISSUE TITLE
"No start line" PEM error

### ISSUE THREAD

**Issue by chazdiezal** [awslabs/amplify-video#191]
**Describe the bug**
Video will not upload in front end.

**To Reproduce**
1. Hitting create asset button in admin panel I get the following error.  I checked the private key and it does contain the proper begin and end formatting.

admin:1 Uncaught (in promise) 
{data: {…}, errors: Array(1)}
data:
createVideoObject: {id: "0a7b4ab3-9421-4553-8ee8-1bdf03e96e3d", token: null, createdAt: "2021-01-28T00:51:22.120Z", updatedAt: "2021-01-28T00:51:22.120Z"}
__proto__: Object
errors: Array(1)
0:
data: null
errorInfo: null
errorType: "Lambda:Unhandled"
locations: [{…}]
message: "error:0909006C:PEM routines:get_name:no start line"
path: (2) ["createVideoObject", "token"]
__proto__: Object
length: 1
__proto__: Array(0)
__proto__: Object

**Expected behavior**
Video should upload and start backend process

**Comment by chazdiezal** [comment]
Here is the Cloudwatch log for VodAws-prod-tokenGen
[pem_error.txt](https://github.com/awslabs/amplify-video/files/5906061/pem_error.txt)

**Comment by wizage** [comment]
Should be fixed in #201

**Comment by chazdiezal** [comment]
now seeing this error when going through running amplify init...

chazdiezal:~/environment/VodAws $ amplify init
Note: It is recommended to run this command from the root of your app directory
? Enter a name for the project VodAws
? Enter a name for the environment prod
? Choose your default editor: None
? Choose the type of app that you're building javascript
Please tell us about your project
? What javascript framework are you using react
? Source Directory Path:  src
? Distribution Directory Path: build
? Build Command:  npm run-script build
? Start Command: npm run-script start
Using default provider  awscloudformation
init failed
{ /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/relay-compiler/lib/transforms/SkipRedundantNodesTransform.js:1
Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/relay-compiler/lib/transforms/SkipRedundantNodesTransform.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/@graphql-toolkit/relay-operation-optimizer/index.cjs.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/lib/visitors/appsync-swift-visitor.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/lib/plugin.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/lib/index.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/utils/getCodegenPackage.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/utils/index.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/types.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/index.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/graphql-codegen.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/index.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/lib/init-steps/s2-initProviders.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/lib/commands/init.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/lib/index.js
- /home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/bin/amplify
    at Object.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/relay-compiler/lib/transforms/SkipRedundantNodesTransform.js:13:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
  code: 'MODULE_NOT_FOUND',
  requireStack:
   [ '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/relay-compiler/lib/transforms/SkipRedundantNodesTransform.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/@graphql-toolkit/relay-operation-optimizer/index.cjs.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/@graphql-codegen/visitor-plugin-common/index.cjs.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/lib/visitors/appsync-swift-visitor.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/lib/plugin.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen-appsync-model-plugin/lib/index.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/utils/getCodegenPackage.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/utils/index.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/commands/types.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-codegen/src/index.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/graphql-codegen.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/push-resources.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/amplify-service-migrate.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/initializer.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/lib/index.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/lib/init-steps/s2-initProviders.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/lib/commands/init.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/lib/index.js',
     '/home/ec2-user/.nvm/versions/node/v10.23.3/lib/node_modules/@aws-amplify/cli/bin/amplify' ] }
chazdiezal:~/environment/VodAws $

**Comment by wizage** [comment]
Hey @chazdiezal 

This looks like an Amplify CLI problem. Can you open a ticket on their repo:

https://github.com/aws-amplify/amplify-cli
