### ISSUE TITLE
setup-obs server URI is incorrect

### ISSUE THREAD

**Issue by smp** [awslabs/amplify-video#209]
**Describe the bug**
setup-obs stream server URL is incorrect

**To Reproduce**
1. create a live video resource using elemental, mediapackage, and no cloudfront distribution. 
2. run amplify video setup-obs
3. select profile and start stream in obs (it will fail)

Note the duplicate protocols in the stream URI, in my case it looked like..

_rtmps://rtmp://IPADDRESSS:1935/mpharvester-dev-p_

**Expected behavior**
Stream should "just start" when I open OBS, select profile, and start stream

**Desktop (please complete the following information):**
 - OS: Mac Catalina

**Comment by nathanagez** [comment]
@smp it looks like the PR I opened weeks ago fix your issue: https://github.com/awslabs/amplify-video/pull/185

**Comment by smp** [comment]
Thanks, closing as duplicate
