### ISSUE TITLE
CI/CD with Amplify Video Category

### ISSUE THREAD

**Issue by danielvouch** [awslabs/amplify-video#224]
Hi,

We are using amplify-category-video@3.2.1 at the moment - we have not upgraded as we could not deploy using version 3.3.0 (another issue) and are using the Default HLS Adaptive Bitrate option, we are also using signed URLs. 

We have 3 environments prod, staging and dev which are all in seperate AWS accounts - the deployment workflow goes dev -> staging -> prod.

So far it has all worked really well for us, however, we are unable to implement a seamless CI/CD pipeline as we are required to update the necessary video category files with the correct configurations for our given environments. 

Ideally we would update the CloudFormation template that creates our video resource but the CloudFormation template is auto-generated and we are unable to change it as our changes will just get overwritten on a new push. 

What is the suggested way to go about this?

Thanks in advance!

**Comment by smp** [comment]
@danielvouch sorry I didn't have any specific recommendations here. Did you close this because you found a solution? If so, could you share? Thanks!

**Comment by danielvouch** [comment]
@smp Unfortunately not, but I saw that there was a PR that looks like it could fix the issue we are having.. https://github.com/awslabs/amplify-video/pull/255#issue-631711160
