### ISSUE TITLE
`The Amplify CLI can NOT find command:  video add`

### ISSUE THREAD

**Issue by hamiltop** [awslabs/amplify-video#23]
**Describe the bug**
Amplify CLI can't find plugin

**To Reproduce**
1. `npm install @aws-amplify/cli -g`
2. output of `amplify --version`: `3.9.0`
3. `npm install amplify-category-video -g`
4. `amplify init`
5. `amplify video add`
6. Get error `The Amplify CLI can NOT find command:  video add`

**Expected behavior**
Expect it to all user to configure the video plugin

**Desktop (please complete the following information):**
 - OS: Mac OSX

**Comment by wizage** [comment]
Fixed in #24
