### ISSUE TITLE
Availability for Flutter?

### ISSUE THREAD

**Issue by djsjr** [awslabs/amplify-video#232]
After successfully running "npm i amplify-category-video -g" (0 vulnerabilities),  I try to add the video category to my flutter app and get "The Amplify CLI can NOT find command:  video add". Is this because Amplify video is not yet available for flutter?

If not, is it coming soon?

**Comment by wizage** [comment]
Hey @djsjr 

Sometimes this happens, you need to run this:
`amplify plugin add` 

The location of the plugin is where your npm global installs too: https://stackoverflow.com/a/5926706

**Comment by djsjr** [comment]
Thanks! Worked.
