### ISSUE TITLE
Migrate all existing console.log to amplify logging solution context.print

### ISSUE THREAD

**Issue by wizage** [awslabs/amplify-video#25]
**Is your feature request related to a problem? Please describe.**
Right now we use `console.log` and `context.print` throughout the project. We should move to using a single unified way of logging.

With `context.print` you can get easily get different colors and bolding that will be unify across amplify. 

Right now Amplify supports:
info - Displays info (White)
warning - Displays a warning (Yellow)
error - Displays an error (Red)
success - Displays a success message (Green)
green - Displays text in Green
yellow - Displays text in Yellow
red - Displays text in Red
blue - Displays text in Blue (This should be used for outputs.)

**Describe the solution you'd like**
Replace the `console.log` with the respective output that you would expect. Can keep the strings the same with chalk formatting (as long as coloring is removed).

**Comment by smp** [comment]
coloring should come from context.print.foo, not from chalk
