### ISSUE TITLE
resource name is "undefined" in v3.6.0

### ISSUE THREAD

**Issue by suzkosh** [awslabs/amplify-video#263]
**Describe the bug**
The resource name is "undefined" in the AWS Elemental Live Stream setup in v3.6.0.

**To Reproduce**
1. install latest(3.6.0) plugin(npm install -g amplify-category-video)
2. interactive cli setup(I select "AWS Elemental Live Stream")
3. you can see video's resource name is "undefined" on "amplify status"

**Expected behavior**
 I expected to be set the resource name that input name in question - "Provide a friendly name for your resource to be used as a label for this category in the project"

**Screenshots**
![image](https://user-images.githubusercontent.com/84467939/120109849-225a3080-c1a6-11eb-96f4-11498f94d64c.png)
![image](https://user-images.githubusercontent.com/84467939/120110104-36526200-c1a7-11eb-9439-e890ff796fff.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I reinstall v3.5.0, and try same steps. v3.5.0 worked as expected.

**Comment by wizage** [comment]
Fixed in 3.7.0
