### ISSUE TITLE
AWS Video Export not updating with Amplify CLI v5.0.0

### ISSUE THREAD

**Issue by mojansen** [awslabs/amplify-video#282]
**Describe the bug**
After upgrading the Amplify CLI to version 5.0.0 (also happens with v5.0.1) the aws-video-exports.js is not updated and throws the error seen in the screenshot below when running `amplify video get-info`.

**To Reproduce**
1. Install `@aws-amplify/cli@5.0.1` and `amplify-category-video@3.7.0`
2. Run `amplify video get-info`
3. Select any project
4. Info is shown correctly but error is thrown and aws-video-export.js isn't updated.

**Expected behavior**
Update aws-video-export.js with the correct config as with previous versions.

**Screenshots**
<img width="1229" alt="Bildschirmfoto 2021-06-20 um 17 16 34" src="https://user-images.githubusercontent.com/59696917/122679477-547e1180-d1eb-11eb-8178-284366635dac.png">

**Comment by wizage** [comment]
I have an update pending release that fixes that. Will be out Monday.

**Comment by mojansen** [comment]
Awesome, thank you!

**Comment by wizage** [comment]
This fix is released as of 3.8.0

Please confirm :)

**Comment by mojansen** [comment]
Yes, it's fixed with 3.8.0. Thank you for the quick help! :)
