### ISSUE TITLE
Stuck on "Copying video resources. This may take a few minutes..." when running amplify push

### ISSUE THREAD

**Issue by djsjr** [awslabs/amplify-video#302]
**Describe the bug**
When I run amplify push, the first message I get is "Copying video resources. This may take a few minutes...". The progress animation is moving but it never finishes. It has been quite a long time. (I have recently updated to Flutter's new null-safety. See additional context at bottom as to why this could be an issue.)

**To Reproduce**
1. Run 'amplify push'

**Expected behavior**
This usually takes no longer than a few moments. 

**Screenshots**
<img width="508" alt="Screen Shot 2021-08-20 at 5 23 28 PM" src="https://user-images.githubusercontent.com/78236971/130294860-cfd447bc-cfe6-435b-a592-6e3a09a73257.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: safari
 - Version: 11.4

**Smartphone (please complete the following information):**
n/a

**Additional context**
I have recently upgraded to Flutter 2.2.3 null-safety. In doing so, my code all had to be converted to the null-safety format. Codegen did this automatically for my models.
e.g.
```
class VideoObject extends Model {
  static const classType = const _VideoObjectModelType();
  final String id;
  final String? _token;
...
```
Notice the edition of ? after the String. These changes work just fine, but perhaps they're causing the problem.

**Comment by wizage** [comment]
Amplify push, just literally run s3 push. It might hang due to internet issues, or credentials issues. Would recommend check your internet and making sure your credentials can push to S3.
