### ISSUE TITLE
Deployment Failed when Deploying from Admin UI After Adding Amplify Video to Schema

### ISSUE THREAD

**Issue by djsjr** [awslabs/amplify-video#322]
**Describe the bug**
Attempting to deploy the GraphQL schema (leaving alone the VodAsset and video object models) from the Admin UI fails. Everything works however. vodAsset object can be created and retrieved.
"Deployment failed 10/13/2021, 3:38:22 PM: Parameters: [secretPemArn, secretPem, publicKey, rPublicName, publicKeyName] must have values."

I tried deleting the amplify video models from the schema, and was able to deploy successfully. I believe deployment from the command line still works. 

Secondly, under the content tab, VodAsset title and description appear blank (appearing as "-"). However they are not. They exist when I check DynamoDB and are successfully retrieved from the app.

**To Reproduce**
1. Go to Data section in Admin UI
2. Click Deploy
3. Watch it fail

**Expected behavior**
Successful Deploy.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser safari
 - Version 

**Smartphone (please complete the following information):**
 - Device: n/a
 - OS:  n/a
 - Browser  n/a
 - Version  n/a

**Additional context**
n/a

**Comment by katsikas-kostas** [comment]
Hi @djsjr actually I had the same issue.
Once I enabled AdminUI then I tried `amplify video build` and then `amplify push` as described at the [wiki](https://github.com/awslabs/amplify-video/wiki/Troubleshooting#q-why-do-my-resources-fail-to-deploy-) 
and in my surprise  😮  I was able to deploy successfully 😃  
I don't know if there is something that Amplify AdminUI team changed in the mid time but know works like a charm  🤗

**Comment by djsjr** [comment]
@katsikas-kostas Hm doesn't seem to work for me. Did you make any changes to the video resource itself? Amplify push says no changes detected when I run these two commands without making any changes.

I did amplify video build, then made a change to another unrelated resource and ran amplify push, but did not fix the UI problem.

**Comment by katsikas-kostas** [comment]
@djsjr Well, yes I have modified a Lambda function to suits my needs. Simply by creating a `/custom` folder and copying the original function from the `/build` folder. 
I also added some additional `@auth` permissions at the `VideoObject` model to match the ones in my others models in the schema. I 'm no exactly sure which of those two things made the difference or maybe it was both of them.
