### ISSUE TITLE
Failed compiling GraphQL schema: Your GraphQL Schema is using "@connection" directive from an older version of the GraphQL Transformer.

### ISSUE THREAD

**Issue by cfzimmerman** [awslabs/amplify-video#339]
### Describe the bug
Following Amplify Video docs to try it out on a test project: https://docs.amplify-video.com/docs/Video-on-Demand/Getting-Started-with-VOD
Allowing "Video Add" to create a new GraphQL API generates a model containing an @ connection, which Amplify flags as outdated, preventing deployment of any Amplify Video resources. The offending @ connection line is directly preceded by a DO NOT EDIT comment. 
Is this an item that needs to be updated from the Amplify Video side, or can I just adjust the written relationship to be consistent with GraphQL transformer v2? If so, what relationship is best?

Also, replacing the @ connection with a v2 relationship like @ hasOne bypasses this error but brings me to this error next: https://github.com/aws-amplify/amplify-cli/issues/3480. Unsure if they're related. There's also an Amplify depreciation warning present, but, again, unsure if that's wrapped up in this. 

### To Reproduce
1. Set up project: Create bare Expo app (Javascript); create new Amplify App via AWS console; deploy basic Auth, Storage, and Data Model via Amplify Studio; pull to local environment; configure boilerplate UI for functional authentication
2. npm i amplify-category-video -g
3. Amplify video add

> Video-On-Demand
> Friendly Name: testvideovod
> Default HLS Adaptive Bitrate
> Notifications: N
> Production: N
> Do you want Amplify to create a new GraphQL API to manage your videos (Beta): Y
> Permission schema: Any authenticated users can upload videos
> Do you want to override your GraphQL schema: N

### Expected behavior
GraphQL compiles so that "amplify push" can be used to generate cloud resources.

### Versions:
- Desktop: Macbook Pro, MacOS Monterey
- Editor: VSCode
- Expo version: 5.3.0
- Amplify version:  7.6.25
- GraphQL transformer version: 2
- amplify-category-video version: 3.9.2

### Screenshots
amplify/backend/api/testvideo/schema.graphql
<img width="696" alt="schema-graphql" src="https://user-images.githubusercontent.com/70831620/159048280-dc927166-4f91-4386-8a7c-64f9b1e1fd64.png">

@ connection error
<img width="1448" alt="@connection-error" src="https://user-images.githubusercontent.com/70831620/159048383-cf33c715-2a42-45cb-940b-1fa1e06c9478.png">

userpools error
<img width="920" alt="userpools-error" src="https://user-images.githubusercontent.com/70831620/159048449-7f01711d-18d4-4fc8-b66f-835a58bdd305.png">

_*** Extra spaces are added between GraphQL @ relationships in this bug report to avoid @-ing other GitHub users with those usernames._

**Comment by luciano-schirmer** [comment]
Based on [GraphQL Transformer v1 to v2 migration](https://docs.amplify.aws/cli/migration/transformer-migration/), we should probably need to change the `video:VideoObject @connections` to `video:VideoObject @hasOne`.

But this still gives the same error message in my machine.

**Comment by luciano-schirmer** [comment]
As a workaround is to replace the following auth rules:

```javascript
@auth(
  rules: [
    {allow: public, groups:["Admin"], operations: [create, update, delete, read]},
    {allow: private, operations: [read]}
  ]
)
```

by this:

```javascript
@auth(
  rules: [
    {allow: public, operations: [read]}
  ]
)
```

At least I was able to proceed with no errors.

**Comment by cfzimmerman** [comment]
Works beautifully. Thank you!
