### ISSUE TITLE
Support for File-Based Inputs for Live Streaming

### ISSUE THREAD

**Issue by smp** [awslabs/amplify-video#38]
**Is your feature request related to a problem? Please describe.**
It would be useful to allow amplify video users to input a file based source for their live stream. Initially we could simply support a 'looped file' mode that would simply loop the source provided via HTTP URI. In the future, we'd want to support mixed file + live sources so that users could control pre/post rolls in addition to a live source.

**Describe the solution you'd like**
Implement FILE_URI in [flagfish.js](https://github.com/wizage/ElementalLambdaDeploy/blob/master/lib/flagfish.js#L224) and add it as an option in the CLI question flow in https://github.com/awslabs/amplify-video/blob/master/provider-utils/livestream-questions.json

**Comment by abhjaw** [comment]
I have created a pull request with a fix to this.

**Comment by wizage** [comment]
Published in v2.5.0
