### ISSUE TITLE
Cloudfront Distro Fails to Push

### ISSUE THREAD

**Issue by smp** [awslabs/amplify-video#40]
**Describe the bug**
Adding a livestream resource with mediapackage+mediastore and cloudfront enabled does not deploy correctly.
**To Reproduce**
a45e60f3f245:cf-test przybill$ amplify add video
? Please select from one of the below mentioned services: Livestream
? Provide a friendly name for your resource to be used as a label for this category in the project: mylivestream
? Do you want to modify any advanced video encoding parameters? No
? Input Security Group:  0.0.0.0/0
? MediaLive ingest type:  RTMP_PUSH
? Encoding Profile:  FULL (6 renditions)
? Auto Start:  Yes
? Where do you want to stream to? MediaPackage & MediaStore
? Output streaming standards. MediaPackage supports HLS, DASH, MSS, and/or CMAF:  HLS,DASH
? Specify catch-up TV window:  86400
? Create distribution:  Yes

### AMPLIFY PUSH OUTPUT BELOW ###

⠹ Updating resources in the cloud. This may take a few minutes...

UPDATE_IN_PROGRESS          amplify-cf-test-dev-123132 AWS::CloudFormation::Stack Fri Nov 08 2019 12:52:31 GMT-0800 (Pacific Standard Time) User Initiated
CREATE_IN_PROGRESS          videomylivestream          AWS::CloudFormation::Stack Fri Nov 08 2019 12:52:34 GMT-0800 (Pacific Standard Time)
CREATE_FAILED               videomylivestream          AWS::CloudFormation::Stack Fri Nov 08 2019 12:52:35 GMT-0800 (Pacific Standard Time) Parameter 'pEnableDistribution' must be one of AllowedValues
UPDATE_ROLLBACK_IN_PROGRESS amplify-cf-test-dev-123132 AWS::CloudFormation::Stack Fri Nov 08 2019 12:52:36 GMT-0800 (Pacific Standard Time) The following resource(s) failed to create: [videomylivestream].
⠸ Updating resources in the cloud. This may take a few minutes...

UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS amplify-cf-test-dev-123132 AWS::CloudFormation::Stack Fri Nov 08 2019 12:53:01 GMT-0800 (Pacific Standard Time)
⠸ Updating resources in the cloud. This may take a few minutes...

DELETE_COMPLETE          videomylivestream          AWS::CloudFormation::Stack Fri Nov 08 2019 12:53:02 GMT-0800 (Pacific Standard Time)
UPDATE_ROLLBACK_COMPLETE amplify-cf-test-dev-123132 AWS::CloudFormation::Stack Fri Nov 08 2019 12:53:02 GMT-0800 (Pacific Standard Time)
⠏ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
⠏ Updating resources in the cloud. This may take a few minutes...

Following resources failed

✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occured during the push operation: Resource is not in the state stackUpdateComplete

**Expected behavior**
Resource should succeed to push.

**Comment by wizage** [comment]
Can you provide this file from your project:

`amplify/video/<project_name>/<project_name>-livestream-workflow.template`

**Comment by smp** [comment]
Turning off cloudfront distro didn't seem to solve problem. Template attached (from run with cf enabled).

[mystream-livestream-workflow copy.template.txt](https://github.com/awslabs/amplify-video/files/3826280/mystream-livestream-workflow.copy.template.txt)
