### ISSUE TITLE
Documentation: Sample IAM Policies for using this plugin

### ISSUE THREAD

**Issue by alcousins** [awslabs/amplify-video#62]
**Is your feature request related to a problem? Please describe.**
Amplify provides a sample IAM Policy for base services at https://aws-amplify.github.io/docs/cli-toolchain/usage#iam-policy-for-the-cli

It would be desirable to include an equivalent policy for the Live and VOD components of Amplify video

**Describe the solution you'd like**
Sample JSON files with appropriate IAM Policies for using these capabilities in an Amplify project

**Describe alternatives you've considered**
Alternatives are to either use Administrator policy, or to experiment with existing Managed Policies related to MediaPackage, MediaConvert etc. There is likely an opportunity to provide a more tightly scoped policy than these broad ones.

**Comment by wizage** [comment]
Will add this to the wiki for docs 👍 

Would you want a full one for all of Amplify Video or for each component (Live and VoD)?

**Comment by wizage** [comment]
https://github.com/awslabs/amplify-video/wiki/IAM-Permissions

Documented here!
