### ISSUE TITLE
Accelerated transcode option

### ISSUE THREAD

**Issue by axptwig** [awslabs/amplify-video#70]
**Is your feature request related to a problem? Please describe.**

Some users would like to make use of accelerated transcode pipelines in order to speed up transcoding long video files.

**Describe the solution you'd like**

Possibly change the lambda code to use accelerated transcode and add a question:

 "do you want to use accelerated transcode?(Y/N)"
 
Implemented possibly like this in the python call? 
AccelerationSettings={
        'Mode': 'PREFERRED'
    },

One of the choices for both production and non prod environments should have an option

**Describe alternatives you've considered**

**Additional context**

**Comment by wizage** [comment]
This is issue will need to be implemented in Python and in Node. See #60.

**Comment by axptwig** [comment]
fixed by #79
