### ISSUE TITLE
Change from output folder to ${id} for placement of files

### ISSUE THREAD

**Issue by wizage** [awslabs/amplify-video#71]
**Is your feature request related to a problem? Please describe.**
Files should be placed in the respective folders/keys instead of placing them in just a broad output/ key.

**Describe the solution you'd like**
Replace output with ${id}

**Files this will effect for sure**
- Token generator lambda
- Job kick off lambda

**Docs will need to be updated**

**Comment by smp** [comment]
Fixed in #86
