### ISSUE TITLE
RTSP

### ISSUE THREAD

**Issue by rudyhadoux** [awslabs/amplify-video#92]
Hi, does it work for RTSP webcams too ?

**Comment by wizage** [comment]
Hello @rudyhadoux 

Today it doesn't support RTSP webcams.

What use case are you going with?

**Comment by rudyhadoux** [comment]
I would like to to create a webcam handling website.
To supervise and store RTSP streams.

**Comment by wizage** [comment]
Hey @rudyhadoux that sounds like a great use case. We can't support it at this time so I am going to close the issue. We will revisit it, if any of our media services support RTSP. 

Thanks,
Sam Patzer
