### ISSUE TITLE
New amplify environment creation is failing

### ISSUE THREAD

**Issue by davep76** [awslabs/amplify-video#95]
**Describe the bug**
I am using amplify (api, auth, video: npm install -g amplify-category-video) to create Video on demand single page application. I have created and deployed the app using CLI in dev environment. Now I want to create a prod environment by using below steps:

amplify env add prod
Base stack gets created
amplify push
It fails with below message
CREATE_IN_PROGRESS amplify-vodemand-prod-182909-videovodemand-177J3HP6VWX6D-rS3OutputBucket-EXHKMX1GY47G AWS::CloudFormation::Stack Wed Apr 22 2020 18:30:48 User Initiated
CREATE_IN_PROGRESS OutputBucket AWS::S3::Bucket Wed Apr 22 2020 18:30:51 GMT+0000 (Coordinated Universal Time)
CREATE_FAILED OutputBucket AWS::S3::Bucket vodemand-dev-output-6dcnv1y6 already exists in stack arn:aws:cloudformation:us-east-1:XXXXXXXX:stack/amplify-vodemand-dev-132429-videovodemand-1E7142Q2DTMT0-rS3OutputBucket-19CWIVGBI84EH/01dc03f0-8242-11ea-af31-0ec446493c7d
CREATE_FAILED amplify-vodemand-prod-182909-videovodemand-177J3HP6VWX6D-rS3OutputBucket-EXHKMX1GY47G AWS::CloudFormation::Stack Wed Apr 22 2020 18:30:52 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to create: [OutputBucket].

Following resources failed

Resource Name: OutputBucket (AWS::S3::Bucket)
Event Type: create
Reason: myvodstreams-dev-output-ll6yvsv4 already exists in stack arn:aws:cloudformation:us-east-1:XXXXXXXXX:stack/amplify-vod-dev-200807-videomyvodstreams-15S1QGUQGGMUX-rS3OutputBucket-1LWO35RPVZYR2/90dacba0-84d5-11ea-8fdd-0ed4cff9b69d

Resource Name: JobTemplate (AWS::MediaConvert::JobTemplate)
Event Type: create
Reason: Amplify_Video_Ott_Hls_Ts_Avc_Aac-myvodstreams-dev already exists in stack arn:aws:cloudformation:us-east-1:XXXXXXX:stack/amplify-vod-dev-200807-videomyvodstreams-15S1QGUQGGMUX-rMediaConvertTemplate-1R9Z6HB1TZABW/90bf2d50-84d5-11ea-90c1-0a39c55408a9
Ideally it should create new buckets as its a new prod environment and I am not sure why it says bucket exists of existing dev environment

Also when I am switching environment there is no change in below 2 folders:

amplify/backend
2.amplify/#current-cloud-backend
I tried many times by creating new environment name but but it keeps on happening

Amplify CLI Version
4.18.0
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Using Linux Cloud 9
node version : v10.20.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wizage** [comment]
The bucket name currently doesn't swap, there is a change in the pipeline to fix this.

To manually change in the mean time you can go to props.json in your amplify/backend/video/<projectname> folder and change the input and output bucket names.

After you change the bucket names you can run `amplify video setup` and then `amplify push` again and it should work!

**Comment by davep76** [comment]
@wizage. Thanks for your response, but still facing the same issue. 
Also "Amplify_Video_Ott_Hls_Ts_Avc_Aac-unicornflix-dev exists" issue along with bucket exists issue 

I tried below steps:
1. Changed input and output bucket name in props.json under amplify/backend/video
2. amplify video setup 
   overwrite all files : I tried with both Yes and No. Fails with the same issue. 
3. amplify push

Error logs

Resource Name: JobTemplate (AWS::MediaConvert::JobTemplate)
Event Type: create
Reason: Amplify_Video_Ott_Hls_Ts_Avc_Aac-unicornflix-dev already exists in stack arn:aws:cloudformation:us-east-1:XXXXXXXX:stack/amplify-unicornflix-dev-81154-videounicornflix-1Q5PRH3TR51JQ-rMediaConvertTemplate-YCLIMWUND0UB/512c4a90-8216-11ea-a542-0e2470ba0d5b


Resource Name: InputBucket (AWS::S3::Bucket)
Event Type: create
Reason: unicornflix-dev-input-zw3ys724 already exists in stack arn:aws:cloudformation:us-east-1:XXXXXXXX:stack/amplify-unicornflix-dev-81154-videounicornflix-1Q5PRH3TR51JQ-rS3InputBucket-1O8NG7YJP9JJX/51078480-8216-11ea-9ed2-126bf0867249


Resource Name: OutputBucket (AWS::S3::Bucket)
Event Type: create
Reason: unicornflix-dev-output-zw3ys724 already exists in stack arn:aws:cloudformation:us-east-1:XXXXXXXXXXX:stack/amplify-unicornflix-dev-81154-videounicornflix-1Q5PRH3TR51JQ-rS3OutputBucket-1JQ1VRFWTH5PS/510f4cb0-8216-11ea-b652-0a0207fddeaf 

Please advice

**Comment by wizage** [comment]
🤦 ahhhh that is a new bug. Thanks for pointing this out. 

I will add this to my fix!

if you go to this `amplify/backend/video/<projectname>/mediaconvert-job-temp.json` and change the name field from `Amplify_Video_Ott_Hls_Ts_Avc_Aac-unicornflix-dev` to `Amplify_Video_Ott_Hls_Ts_Avc_Aac-unicornflix-dev2`.

I am just getting to this section of the beta evaluation so this helps me a ton! Thanks so much for your contributions!

**Comment by davep76** [comment]
@wizage Thanks for you quick response. Manual workarounds are not working for s3 buckets and media convert as well. They are throwing up the same issue
Please advice

**Comment by davep76** [comment]
@wizage please let me know if there is any update or timeline for the fix?

**Comment by wizage** [comment]
Changes that are going to be made to better support this:

**Comment by wizage** [comment]
Fix is in the pipeline and needs to be reviewed. Hopefully this will fix the issue. I have walked through your use case and now I don't see any issues :) Sorry about the delay, I wanted to do it right.

**Comment by wizage** [comment]
Beta is now available at `npm i amplify-category-video@beta -g`
